export type CompanionLanguage = "en" | "zh";

export const companionCopy = {
  en: {
    fallbackName: "Companion",
    house: "House",
    subtitle: "A personal space for encouragement, reflection, and growth.",
    dashboard: "View",
    timeline: "Plan",
    profile: "Profile",
    level: "Level",
    xp: "XP",
    type: "Companion type",
    today: "Today's corner",
    todayText: "Review what matters today and take one small step forward.",
    journey: "Growth journey",
    journeyText: "Completed tasks and milestones become part of the shared journey.",
    memories: "Memories",
    memoriesText: "Important growth moments can be collected here in a future update.",
    talk: "Talk with companion",
    talkText: "Conversation features can be connected here when the companion service is ready.",
    viewTasks: "View tasks",
    viewTimeline: "View timeline",
    customize: "Customize companion",
    notSelected: "No companion has been selected yet.",
    choose: "Choose a companion",
  },
  zh: {
    fallbackName: "伙伴",
    house: "小屋",
    subtitle: "属于伙伴的陪伴、回顾与成长空间。",
    dashboard: "查看",
    timeline: "规划",
    profile: "个人资料",
    level: "等级",
    xp: "经验值",
    type: "伙伴类型",
    today: "今日角落",
    todayText: "回顾今天真正重要的事情，再向前走一小步。",
    journey: "成长旅程",
    journeyText: "完成的任务和里程碑会成为共同成长旅程的一部分。",
    memories: "成长回忆",
    memoriesText: "未来可以在这里收藏重要的成长时刻。",
    talk: "与伙伴交流",
    talkText: "伙伴对话服务准备完成后，可以从这里接入。",
    viewTasks: "查看任务",
    viewTimeline: "查看时间线",
    customize: "设置伙伴",
    notSelected: "尚未选择成长伙伴。",
    choose: "选择伙伴",
  },
} as const;
